/**
 *
 * @author Gabriel
 */
public class AdivinhacaoDeNumero extends javax.swing.JFrame {

    /**
     * Creates new form AdiviacaoDeNumero
     */
    public AdivinhacaoDeNumero() {
        initComponents();
        lblRes.setText("<html>Adivinhe o número que estou pensando</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnPalp = new javax.swing.JButton();
        txtNum = new javax.swing.JSpinner();
        lblRes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/akinator_1_defi1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 483));

        btnPalp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPalp.setForeground(new java.awt.Color(0, 0, 255));
        btnPalp.setText("Palpiter");
        btnPalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 506, -1, -1));

        txtNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 506, -1, -1));

        lblRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRes.setText("frase");
        lblRes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2043.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 267));

        pack();
    }// </editor-fold>                        

    private void btnPalpActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        double n = 1 + Math.random() * (11-1);
        int valor = (int) n;
        
        int num = Integer.parseInt(txtNum.getValue().toString());
        
        String f1 = "<html>Acertou!</html>";
        String f2 = "<html>Errou! Eu pensei no valor "+valor+"</html>";
        String res = (valor == num)?f1:f2;
        
        lblRes.setText(res);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdivinhacaoDeNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdivinhacaoDeNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdivinhacaoDeNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdivinhacaoDeNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdivinhacaoDeNumero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPalp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRes;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration                   
}
